CREATE TABLE [dbo].[Table]
(
	[email] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [nama] VARCHAR(50) NULL,
	[soal1] int NULL,
	[soal2] int NULL,
	[soal3] int NULL,
	[soal4] int NULL,
	[soal5] int NULL,
	[soal6] int NULL,
	[soal7] int NULL,
	[soal8] int NULL,
	[soal9] int NULL,
	[soal10] int NULL,
	[salah1] int NULL,
	[salah2] int NULL,
	[salah3] int NULL,
	[salah4] int NULL,
	[salah5] int NULL,
	[salah6] int NULL,
	[salah7] int NULL,
	[salah8] int NULL,
	[salah9] int NULL,
	[salah10] int NULL,
	[rank] int NULL
)
